### ISSUE TITLE
Adding ascii text using simple comments breaks project build

### ISSUE THREAD

**Issue by mariogarcia** [pledbrook/lazybones#157]
I have a template of a build.gradle file containing some ascii text of type

<pre>
<code>
//
//  _____  _             _
// |  __ \| |           (_)
// | |__) | |_   _  __ _ _ _ __  ___
// |  ___/| | | | |/ _` | | '_ \/ __|
// | |    | | |_| | (_| | | | | \__ \
// |_|    |_|\__,_|\__, |_|_| |_|___/
//                  __/ |
//                 |___/
//
</code>
</pre>

Once I install the template and try to execute it, it complains saying:

<pre>
<code>
SimpleTemplateScript2.groovy: 3: unexpected char: '\' @ line 3, column 11.
   // |  __ \| |           (_)
             ^

1 error

</code>
</pre>

**Comment by pledbrook** [comment]
The backslash, `\`, is an escape character in Groovy templates. For example, to use a literal '$' in a template, you need to put `\$`, otherwise it's treated as a Groovy expression. The string `\|` is not recognised as an escape sequence, hence why you see the error you do.

You have two options:

1. Escape the backslashes by doubling them up, i.e. `\\`

2. Use Handlebars templates which probably don't treat backslashes as escape sequences, although I'm not sure.

**Comment by mariogarcia** [comment]
Ok thanks for the quick reply Peter. Good explanation. I'll probably try the second one.
