### ISSUE TITLE
sdkman install does not initialise .lazybones directory

### ISSUE THREAD

**Issue by aplatypus** [pledbrook/lazybones#165]
I just installed lazybones via the sdkmanager,

      $  skd install lazybones

And everything looks good.  I can do

      $ lazybones -version
      Lazybones version 0.8.1

Looks good.  When I looked for the config files; there was no config/settings folder created during the install.

*  $USER_HOME/.lazybones/

I think the install script ought to make the directory.  That's OK if it doesn't want to.  In that case though there needs to be some instructions to let people know what to put in there.

For example; is there a lazybones template for the lazybones installation and settings?!

I think it's ironic when a template doesn't template itself :-)    

Is there documentation on what goes into the  `.lazybones` directory?

Thanks,
    Will

**Comment by pledbrook** [comment]
The _~/.lazybones_ directory is initialised as soon as it's required, such as when you first use a template. The README on the project page covers the tool from the user perspective and mentions how you can add additional template package repositories via the _config.groovy_ file. You can also add configuration settings via the `config` command, which is also documented in that README.

I'm not saying that as a RTFM, because I think tools should be as usable as possible without reading docs. And the information can still be presented better (a dedicated website would help too, which someone is kindly working on contributing).

So on to your specific request. As far as I'm aware, SDKman doesn't have install scripts. I can't see anything along those lines in the release API for that tool. That said, does it really make sense to create the directory before it's needed? The only value I can think of is an existing configuration file that documents the various options. But you can run `lazybones config list` to get that information, although I see that it's lacking descriptions for the various settings.

As for the irony, remember that Lazybones is a tool for creating projects from templates. And there is a template for creating Lazybones projects, which are used to create and package other templates. Lazybones itself is not a template.

If you still think that the installation of Lazybones should automatically create the _~.lazybones_ directory, then I would raise this with SDKman, since that performs the installation. If you really think that Lazybones should create a dummy _config.groovy_ the first time it runs, then I'm happy to be persuaded. At the moment, I'm not convinced by the argument. On the other hand, I'd probably accept a pull request implementing the feature, since it doesn't adversely affect anything else.

**Comment by aplatypus** [comment]
Thanks for your repsonse @pledbrook,

I understand (*better*) now.   The only reason I was aware of the `~/.lazybones` directory is that I was following the Griffon quick start.

*  http://griffon-framework.org/

The answer to your question re: 
>  does it really make sense to create the directory before it's needed

As it stands in my home directory:

      ~ $ ls -ldt ~/.l*
      drwx------ 2 william william 4096 Nov 18 21:58 /home/william/.links2
      drwxr-xr-x 3 william william 4096 Sep 16 00:05 /home/william/.linuxmint
      drwxr-xr-x 3 william william 4096 Sep 16 00:05 /home/william/.local

As I didn't want to get into creating things last night (*yet*).  

While at the same time, liberal use of help  and hacking about yields this:

      ~ $ lazybones config show --all 
      Current configuration settings:
      
          config.file           = /home/william/.lazybones/config.groovy
          cache.dir             = /home/william/.lazybones/templates
          bintrayRepositories   = [pledbrook/lazybones-templates]

And I detect a theme here that there's a `config.file` and  `cache.dir` in a folder called, "`~/.lazybones`".

I was not understanding; and my question was motivated by a feeling that something was awry.  I do agree the readme, needs to identify making the `~/.lazybones` folder as an optional step.  I gather the default values are internal to the code or libraries.

Per my jibe about a lazybones template ... I think it is worth consideration.  The thing I was (*mistakenly*) looking for last night was something like a

     git init

With a `lazybone init`, one might call-up a lazybones profile (which is a template) for some purpose such as my Griffon (*ibid*) exercise of this weekend.   Or just a default profile that matched the existing built-in defaults.  To me the benefit of this is you never need to recode new defaults for new features or modify defaults apart from the existing bootstrap values, ever again.  Example:  

      lazybones init [ default ]
      lazybones init griffon-profile

And, that way,  lazybones  may  extend itself in a more or less progressive manner (maintaining a degree of backward-compatible-*ness*).

Such an "`init`" stage might create a .lazybones directory, as required *btw*.  One wouldn't need a dummy file on this level because the `init` stage takes care of that.  With no `init`, the user needs to make the base folder and files, etc.  (fair enough).

Me?  I've always been a lazy programmer.  Why code when a class design or some script will *do my work* for me?  Stay **DRY** -- So even a default profile can look at my Linux, Mac or Windows `env` and git settings to  auto-fill values for obvious stuff.  

Which might identify pragmatic reasons to consider some kind of priming for lazybones when it first runs (even for 'help'), whereby it may ask, 

      `Would you like to use a a named profile, the default  or none (p/d/n) ? _`

At least for me, if I saw that question, I'd know there are things I may do, like reading the README :-)

**Comment by pledbrook** [comment]
You make a couple of interesting points here. I can see where the output of `config show --all` might be confusing when the directory it references doesn't exist. I don't think `git init` is a useful comparison as it doesn't automatically create a `~/.gitconfig` file, which would be the equivalent behaviour.

I would certainly consider automatically creating the relevant directories and files when `lazybones` is first executed. The only downside is that the user ends up with those even if they just run `lazybones --version` and then remove the tool. That may bother some, but I don't know.

The profile idea is intriguing and I'm sure @aalmiray would be interested. At the moment, I think the only information that potentially works in a profile is the Bintray repositories, but such a feature would certainly make it easier to get started with Griffon. I have no idea how profiles would be implemented, but it's something to consider.
